FROM balenalib/raspberrypi3-python

RUN apt-get update && apt-get upgrade -y && \
    apt-get install python3-pip libjpeg-dev \
    libopenjp2-7-dev libtiff-dev libxcb1 \
    libatlas-base-dev libfreetype6-dev

